<?php

namespace Arpanmandaviya\SystemBuilder\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;

class SystemViewCommand extends Command
{
    protected $signature = 'system:view {name? : Name of the view file(s)}';

    protected $description = 'Generate one or multiple Blade views with optional Bootstrap layout.';

    protected $files;

    public function __construct()
    {
        parent::__construct();
        $this->files = new Filesystem();
    }

    public function handle()
    {
        $input = $this->argument('name') ?: $this->ask("Enter view name (Example: dashboard or admin/pages/[home,edit,create])");

        $input = trim($input);
        if (Str::contains($input, ',')) {
            if (!Str::contains($input, ['[', ']'])) {
                $folder = Str::contains($input, '/') ? Str::beforeLast($input, '/') : '';
                $list   = Str::afterLast($input, '/');
                $input  = $folder !== ''
                    ? "{$folder}/[{$list}]"
                    : "[{$list}]";
            }
            $this->processMultipleViews($input);

        } else {
            $this->processSingleView($input);
        }
    }

    private function processMultipleViews($input)
    {
        $folder = Str::before($input, '[');
        $folder = trim($folder, "/ ");

        $rawNames = Str::between($input, '[', ']');
        $names = array_map('trim', explode(',', $rawNames));

        // Filter invalid characters
        $names = array_map(function ($name) {
            return preg_replace('/[^a-zA-Z0-9_-]/', '', $name);
        }, $names);

        $layoutChoice = $this->choice(
            "Choose template for ALL views",
            ['0 = Normal HTML (default)', '1 = Bootstrap 5 Layout'],
            0
        );

        $isBootstrap = Str::contains($layoutChoice, '1');

        foreach ($names as $viewName) {
            $fileName = $this->normalizeFileName($viewName);

            $path = resource_path("views/{$folder}/{$fileName}");

            $this->generateView($path, $fileName, $isBootstrap);
        }

        $this->info("🎉 All view files created in: resources/views/{$folder}/");
    }

    private function processSingleView($name)
    {
        // Check typo only for single file mode
        if (Str::contains($name, ['dashbaord', 'dasboard', 'usr'])) {
            if (!$this->confirm("⚠ The name '$name' looks misspelled. Continue?", false)) {
                $name = $this->ask("Enter corrected name:");
            }
        }

        // Clean invalid characters
        $name = preg_replace('/[^a-zA-Z0-9\/_-]/', '', $name);

        $fileName = $this->normalizeFileName($name);

        $path = resource_path("views/{$fileName}");

        $layoutChoice = $this->choice(
            "Choose view template type",
            ['0 = Normal HTML (default)', '1 = Bootstrap 5 Layout'],
            0
        );

        $isBootstrap = Str::contains($layoutChoice, '1');

        $this->generateView($path, $fileName, $isBootstrap);

        $this->info("✅ View created: resources/views/{$fileName}");
    }

    private function normalizeFileName($name)
    {
        $name = trim($name, "/ ");

        if (!Str::endsWith($name, '.blade.php')) {
            $name .= '.blade.php';
        }

        return $name;
    }

    private function generateView($path, $name, $bootstrap)
    {
        $this->files->ensureDirectoryExists(dirname($path));

        $content = $bootstrap ? $this->bootstrapTemplate($name) : $this->simpleTemplate($name);

        $this->files->put($path, $content);
    }

    protected function simpleTemplate($name)
    {
        $title = ucwords(str_replace(['-', '_', '.blade.php'], ' ', $name));

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{$title}</title>
</head>
<body>

<h1>{$title}</h1>
<p>Generated by System Builder.</p>

</body>
</html>
HTML;
    }

    protected function bootstrapTemplate($name)
    {
        $title = ucwords(str_replace(['-', '_', '.blade.php'], ' ', $name));

        return <<<HTML
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{$title}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body class="bg-light">

<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="text-center">
        <h1 class="fw-bold text-primary">{$title}</h1>
        <p class="lead text-muted">Generated using Laravel System Builder (Bootstrap 5 Layout).</p>
    </div>
</div>

</body>
</html>
HTML;
    }
}
