<?php

namespace Arpanmandaviya\SystemBuilder\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;

class SystemViewCommand extends Command
{
    protected $signature = 'system:view {name? : Name of the view file}';

    protected $description = 'Generate a new Blade view with optional Bootstrap layout.';

    protected $files;

    public function __construct()
    {
        parent::__construct();
        $this->files = new Filesystem();
    }

    public function handle()
    {
        // Step 1: Get view name
        $name = $this->argument('name') ?: $this->ask("Enter view name (Example: dashboard, user-profile)");

        // Step 2: Clean input
        $name = strtolower(trim($name));

        // Step 3: Confirm if name contains potential mistakes
        if (Str::contains($name, ['dashbaord', 'dasboard', 'usr'])) {
            if (!$this->confirm("⚠️ The name '{$name}' looks misspelled. Continue?", false)) {
                $name = $this->ask("Enter corrected name:");
            }
        }

        // Step 4: Ensure .blade.php suffix
        if (!Str::endsWith($name, '.blade.php')) {
            $name .= '.blade.php';
        }

        // Step 5: Prepare full path
        $path = resource_path("views/{$name}");

        // Step 6: If file exists
        if ($this->files->exists($path)) {
            if (!$this->confirm("⚠ View already exists. Overwrite?", false)) {
                return $this->warn("❌ Operation cancelled.");
            }
        }

        // Step 7: Ask layout preference
        $layoutChoice = $this->choice(
            "Choose view template type",
            ['0 = Normal HTML (default)', '1 = Bootstrap 5 Layout'],
            0
        );

        $isBootstrap = Str::contains($layoutChoice, '1');

        // Step 8: Get template content
        $content = $isBootstrap ? $this->bootstrapTemplate($name) : $this->simpleTemplate($name);

        // Step 9: Create directories if needed
        $this->files->ensureDirectoryExists(dirname($path));

        // Step 10: Write file
        $this->files->put($path, $content);

        $this->info("✅ View created: resources/views/{$name}");
    }

    protected function simpleTemplate($name)
    {
        $title = ucwords(str_replace(['-', '_', '.blade.php'], ' ', $name));

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{$title}</title>
</head>
<body>

<h1>{$title}</h1>
<p>Generated by System Builder.</p>

</body>
</html>
HTML;
    }

    protected function bootstrapTemplate($name)
    {
        $title = ucwords(str_replace(['-', '_', '.blade.php'], ' ', $name));

        return <<<HTML
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{$title}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body class="bg-light">

<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="text-center">
        <h1 class="fw-bold text-primary">{$title}</h1>
        <p class="lead text-muted">This view is generated using Laravel System Builder (Bootstrap 5 Layout).</p>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
HTML;
    }
}
